<?php echo $this->form ?>
<?php $this->inlineScript()->appendFile('/js/decision.js') ?>
<?php $this->inlineScript()->captureStart() ?>

$(function() {

    var questions = new DecisionQuiz({
        el: $('#decision-quiz'),
        decisionUrl: '<?php echo $this->url(array(), 'decide') ?>',
        decisionStrategy: 'spanish21'
    });

    questions.render();

});

<?php $this->inlineScript()->captureEnd() ?>
