<?php
// This file generated by Propel  convert-conf target
// from XML runtime conf file C:\Users\User\workspace\Blackjack Practice Application\bin\runtime-conf.xml
return array (
  'datasources' => 
  array (
    'blackjack' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=bj_data',
        'user' => 'root',
        'password' => '',
        'settings' => 
        array (
          'charset' => 
          array (
            'value' => 'utf8',
          ),
        ),
      ),
    ),
    'default' => 'blackjack',
  ),
  'generator_version' => '1.4.2',
  'classmap' => 
  array (
    'QuizTableMap' => 'Bj/map/QuizTableMap.php',
    'QuizPeer' => 'Bj/QuizPeer.php',
    'Quiz' => 'Bj/Quiz.php',
    'QuizQuestionTableMap' => 'Bj/map/QuizQuestionTableMap.php',
    'QuizQuestionPeer' => 'Bj/QuizQuestionPeer.php',
    'QuizQuestion' => 'Bj/QuizQuestion.php',
    'QuizQuestionOptionTableMap' => 'Bj/map/QuizQuestionOptionTableMap.php',
    'QuizQuestionOptionPeer' => 'Bj/QuizQuestionOptionPeer.php',
    'QuizQuestionOption' => 'Bj/QuizQuestionOption.php',
  ),
);